Repository mednajjar/DevSpace, pull requests merged in 2020-01, with the labels that each got.

#3 Ajouter dossier image
  Agence-Web/img/Readme.txt
Labels: bug

#21 my files
  Agence-Web/img/Image33.png
  Agence-Web/img/image11.png
  Agence-Web/img/image22.png
  Agence-Web/img/images44.jfif
  Agence-Web/img/images55.jfif
  Agence-Web/img/images66.jfif
  Agence-Web/index.html
  Agence-Web/style.css
  Mockup/mockupsamir.xd
Labels: Finish

#20 section equipe et client
  Agence-Web/img/CLNT1.png
  Agence-Web/img/CLNT2.png
  Agence-Web/img/CLNT3.png
  Agence-Web/img/CLNT4.png
  Agence-Web/img/CLNT5.png
  Agence-Web/img/CLNT6.png
  Agence-Web/img/user1.png
  Agence-Web/img/user2.png
  Agence-Web/img/user3.png
  Agence-Web/img/user4.png
  Agence-Web/index.html
  Agence-Web/style.css
  Mockup/najjar/section Najjar.xd
Labels: Finish

#16 khadija zahir voici le mockup et codage de la partie pricing
  Agence-Web/img/download.png
  Agence-Web/img/hands.jpg
  Agence-Web/index.html
  Agence-Web/style.css
  Mockup/section pricing_khadija/section pricing khadija.xd
Labels: duplicate
